### ISSUE TITLE
Getting started with experiments

### ISSUE THREAD

**Issue by rahul99** [rahul99/msc_plan#4]
I have gone through some papers to understand how embedding is done. Here is the project milestone. Let me know if any step is missing:

1. Fetch and process data. (Start with one annotated data first)

2. Fetch graph information from the data (this will require data with annotation). (which utility to use?)

3. Once graph is extracted, explore how to change the graph (target graph) in order for the generator to generate meaningful images conditioned on input image and the target graph. 

3. Understand code base of zi2zi to figure out how embedding is done (integrate target graph and condition image): Note that graph dimension per image will be different than the condition image dimension. Hence need to work out how to concatenate the two.

4. Run the initial set of experiment and observe the output of the generator

NOTE: Some of the points are abstract (#3 for example), hence this list will be updated as and when progress is made.

Will work on #1 and #2 starting tomorrow morning. And will keep updating this list.

**Comment by bigaidream** [comment]
As for Step 2, what do you mean by `annotation`? In the Gated Graph Neural Network framework, the annotations are made by hand.

**Comment by rahul99** [comment]
I meant the utility for the second part (extracting graph). I see that, for example, DeepFashion data is already annotated.

Does the flow look as expected or I missed out on my understanding?

**Comment by bigaidream** [comment]
For DeepFashion, since it is already annotated, we don't have to extract graph structure (i.e. adjacency matrix) by ourselves. 

Establishing graph structure is not our key contribution. Actually, as object detectors are usually not reliable, it is better to avoid using them at all. 

So, let's use the existing annotation information for experiments.
