### ISSUE TITLE
Paper to read

### ISSUE THREAD

**Issue by bigaidream** [rahul99/msc_plan#9]
GANs are Broken in More than One Way: The Numerics of GANs

**Comment by rahul99** [comment]
​Not much updates for today. Need little more time to understand the
scene-graph work and make it work. I am going through the code to
understand their h5 data structure (need little more time on that).

Also, it seems for this VG dataset, we will not be able to define "target
image" and "condition image", unless we manually sit and distinguish images
based same time of objects.

But, as suggested by your friend, we can implement the second approach on
this dataset. 2nd approach relies only on input noise and the target graph.
So all the images act as target image.

Thanks,
Rahul
 ​
